import Head from 'next/head'
import Footer from './footer'
import styles from 'styles/Home.module.scss'

export default function Layout ({ children, title }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{ title ?? 'Home' }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        { children }
      </main>

      <Footer />
    </div>
  )
}
